### ISSUE TITLE
Separate HTML, JS, CSS

### ISSUE THREAD

**Issue by cootook** [cootook/project#7]
clean templates

**Comment by isaiahthedev** [comment]
Hi, I can work on this if you want. Don't know if you wanted any help 🤔

**Comment by cootook** [comment]
Cool!
There is a branch for this issue, so you can work there! 
Let me know if you are going to run the whole project or to edit templates only.
Please don't forget to commit changes for each template separately.
Appreciate it!

**Comment by isaiahthedev** [comment]
Awesome, I'll work in the branch you have for this issue. I will be running the project locally, and I'll commit changes for each template separately.

**Comment by isaiahthedev** [comment]
You have a folder called static that contains js and css folders, is that where I should store the new js and css files?

**Comment by cootook** [comment]
That's right

**Comment by isaiahthedev** [comment]
I like the app a lot. I've been messing around with the database and checking everything out. Good job on everything.
